//Nome: Gustavo Miranda
//Student ID: 101488574

//Question 3 - Add Logs

const fs = require('fs/promises');
const path = require('path');

(async () => {
  const logsDir = path.join(__dirname, '..', 'logs');

  try {
    console.log('--------------------------- Question 3 - Add Logs -------------------------------');
    console.log('Create Log files (add)'); 
    console.log(' ');

 
    
    await fs.mkdir(logsDir, { recursive: true });


    
    process.chdir(logsDir);


    


    for (let i = 0; i < 10; i++) {
      const file = `log${i}.txt`;
      const text = `log ${i} - generated by Gustavo Miranda (101488574) at ${new Date().toISOString()}\n`;
      await fs.writeFile(file, text, 'utf8');
    }
    const files = await fs.readdir(process.cwd());
    files.forEach(f => console.log(f));

    console.log(' ');
    console.log('-------------------------------------------------------------------------------');
  } catch (err) {
    console.error('[Add Logs Error]', err.message);
    process.exit(1);
  }
})();